image: maven:3.9.6-eclipse-temurin-21

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn test jacoco:report
  artifacts:
    paths:
      - target/site/jacoco/index.html
    expire_in: 1 week
